version: '3.1'

networks:
  default:
    external: true
    name: traefik-public

services:
  scrapy:
    build:
      context: fpv_products
    restart: always
    environment:
      MONGODB_SERVER: "mongodb://marek:abrakadabra12@mongo:27017/"
      MONGODB_DB: "fpvScrapper"
      MONGODB_COLLECTION: "products"

  front:
    build:
      context: site
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.fpv.rule=Host(`droneparts.me`)
      - traefik.http.services.fpv.loadbalancer.server.port=8000
    environment:
      MONGO_URL: mongodb://marek:abrakadabra12@mongo:27017/fpvScrapper?authSource=admin
    ports:
      - "8080:8000"
  mongo:
    image: mongo:4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./container-data/mongo-data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: marek
      MONGO_INITDB_ROOT_PASSWORD: abrakadabra12

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: marek
      ME_CONFIG_MONGODB_ADMINPASSWORD: abrakadabra12
      ME_CONFIG_MONGODB_URL: mongodb://marek:abrakadabra12@mongo:27017/
