version: '3.1'
services:

  mongo:
    image: mongo:6.0.2
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: marek
      MONGO_INITDB_ROOT_PASSWORD: abrakadabra12

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: marek
      ME_CONFIG_MONGODB_ADMINPASSWORD: abrakadabra12
      ME_CONFIG_MONGODB_URL: mongodb://marek:abrakadabra12@mongo:27017/
